### ISSUE TITLE
Error: Signature not verified!

### ISSUE THREAD

**Issue by thedanik123** [sagar040/proot-distro-nethunter#6]
Whenever I get to the nethunter build stage(where you select build number and install) it seems to be installing it and after a few minutes exits saying:

'Error: signature not verified. Downloaded file flagged as malicious. Exiting'

Any solutions? 
![Screenshot_20241218-130622_Termux](https://github.com/user-attachments/assets/a588a207-de2f-4176-b392-c42f13774d20)

**Comment by sagar040** [comment]
**Issue fixed in version 1.8.2**
**See change log:** https://github.com/sagar040/proot-distro-nethunter?tab=readme-ov-file#change-logs
**Cause of issue:** Signature not verified because resource (https://kali.download/nethunter-images/kali-2024.4/rootfs/) has not yet added sha512 checksum.


Version 1.8.2 will use all resources from `image-nethunter.kali.org`  **See:** https://image-nethunter.kali.org/nethunter-fs/kali-2024.4/


```diff
-    base_url="https://kali.download/nethunter-images/current/rootfs"
-    rootfs="kali-nethunter-rootfs-minimal-$SYS_ARCH.tar.xz"
-    sha512_url="$base_url/$rootfs.sha512sum"
-    SHA512=$(curl -s -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" "$sha512_url" | awk '{print $1}')

+    base_url="https://image-nethunter.kali.org/nethunter-fs/"
+    latest_release_url=$(curl -s "$base_url" | grep -oP '(?<=href=")kali-\d{4}\.\d+/' | sort -V | tail -n 1)
+    if [[ -n "$latest_release_url" ]]; then
+        latest_url="${base_url}${latest_release_url}"
+    else
+        print_error "Failed to retrieve the latest version URL"
+        exit 1
+    fi
+    local y_release=$(echo "$latest_release_url" | sed 's|kali-||; s|/||')
+    rootfs="kali-nethunter-$y_release-rootfs-minimal-$SYS_ARCH.tar.xz"
+    sha512_url="$latest_url$rootfs.sha512sum"
+    SHA512=$(curl -s "$sha512_url" | awk '{print $1}')
```
